# @package _global_

defaults:
  - robot_base

robot:
  num_bodies: 30
  torso_name: "torso_link"
  foot_name: "ankle_roll_link"
  ankle_roll_dof_names: ["left_ankle_roll_joint", "right_ankle_roll_joint"]
  penalize_contacts_on: ["pelvis", "shoulder", "hip"]

  dof_names: [
    "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
    "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
    "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint",
    "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint",
    "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint",
    "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint",
    "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint",
  ]

  body_names: [
    "pelvis",
    "left_hip_pitch_link", "left_hip_roll_link", "left_hip_yaw_link", "left_knee_link", "left_ankle_pitch_link", "left_ankle_roll_link",
    "right_hip_pitch_link", "right_hip_roll_link", "right_hip_yaw_link", "right_knee_link", "right_ankle_pitch_link", "right_ankle_roll_link",
    "waist_yaw_link", "waist_roll_link", "torso_link",
    "left_shoulder_pitch_link", "left_shoulder_roll_link", "left_shoulder_yaw_link", "left_elbow_link",
    "left_wrist_roll_link", "left_wrist_pitch_link", "left_wrist_yaw_link",
    "right_shoulder_pitch_link", "right_shoulder_roll_link", "right_shoulder_yaw_link", "right_elbow_link",
    "right_wrist_roll_link", "right_wrist_pitch_link", "right_wrist_yaw_link",
  ]

  dof_vel_limit_list: [
    32., 32., 32., 20., 37., 37.,
    32., 32., 32., 20., 37., 37.,
    32., 37., 37.,
    37., 37., 37., 37., 37., 22., 22.,
    37., 37., 37., 37., 37., 22., 22.,
  ]
  dof_effort_limit_list: [
    139., 139., 88., 139., 50., 50.,
    139., 139., 88., 139., 50., 50.,
    88., 50., 50.,
    25., 25., 25., 25., 25., 5., 5.,
    25., 25., 25., 25., 25., 5., 5.,
  ]
  dof_armature_list: [
    0.025101925, 0.025101925, 0.01017752004, 0.025101925, 0.00721945, 0.00721945,
    0.025101925, 0.025101925, 0.01017752004, 0.025101925, 0.00721945, 0.00721945,
    0.01017752004, 0.00721945, 0.00721945,
    0.003609725, 0.003609725, 0.003609725, 0.003609725, 0.003609725, 0.00425, 0.00425,
    0.003609725, 0.003609725, 0.003609725, 0.003609725, 0.003609725, 0.00425, 0.00425,
  ]
  dof_joint_friction_list: [
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
    0.03, 0.03, 0.03,
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
  ]

  init_state:
    default_joint_angles:
      left_hip_pitch_joint: -0.1
      left_hip_roll_joint: 0.0
      left_hip_yaw_joint: 0.0
      left_knee_joint: 0.3
      left_ankle_pitch_joint: -0.2
      left_ankle_roll_joint: 0.0
      right_hip_pitch_joint: -0.1
      right_hip_roll_joint: 0.0
      right_hip_yaw_joint: 0.0
      right_knee_joint: 0.3
      right_ankle_pitch_joint: -0.2
      right_ankle_roll_joint: 0.0
      waist_yaw_joint: 0.0
      waist_roll_joint: 0.0
      waist_pitch_joint: 0.0
      left_shoulder_pitch_joint: 0.0
      left_shoulder_roll_joint: 0.0
      left_shoulder_yaw_joint: 0.0
      left_elbow_joint: 0.0
      left_wrist_roll_joint: 0.0
      left_wrist_pitch_joint: 0.0
      left_wrist_yaw_joint: 0.0
      right_shoulder_pitch_joint: 0.0
      right_shoulder_roll_joint: 0.0
      right_shoulder_yaw_joint: 0.0
      right_elbow_joint: 0.0
      right_wrist_roll_joint: 0.0
      right_wrist_pitch_joint: 0.0
      right_wrist_yaw_joint: 0.0

  randomize_link_body_names: [
    "pelvis",
    "left_hip_yaw_link", "left_hip_roll_link", "left_hip_pitch_link", "left_knee_link",
    "right_hip_yaw_link", "right_hip_roll_link", "right_hip_pitch_link", "right_knee_link",
  ]

  control:
    stiffness:
      hip_yaw: 40.17924
      hip_roll: 99.09843
      hip_pitch: 99.09843
      knee: 99.09843
      ankle_pitch: 28.50125
      ankle_roll: 28.50125
      waist_yaw: 300.0
      waist_roll: 300.0
      waist_pitch: 300.0
      shoulder_pitch: 14.25062
      shoulder_roll: 14.25062
      shoulder_yaw: 14.25062
      elbow: 14.25062
      wrist_roll: 14.25062
      wrist_pitch: 16.77833
      wrist_yaw: 16.77833
    damping:
      hip_yaw: 2.55789
      hip_roll: 6.30880
      hip_pitch: 6.30880
      knee: 6.30880
      ankle_pitch: 1.81445
      ankle_roll: 1.81445
      waist_yaw: 5.0
      waist_roll: 5.0
      waist_pitch: 5.0
      shoulder_pitch: 0.90722
      shoulder_roll: 0.90722
      shoulder_yaw: 0.90722
      elbow: 0.90722
      wrist_roll: 0.90722
      wrist_pitch: 1.06814
      wrist_yaw: 1.06814
    action_scale: 0.25
    action_clip_value: 5.0
    action_rescale: true
    normalize_action_from: 1.0
    normalize_action_to: 5.0

  asset:
    usd_file: "g1/g1_29dof_rev_1_0/g1_29dof_rev_1_0.usd"

  motion:
    asset:
      assetRoot: "bfm/data/robots/g1/"
      assetFileName: "g1_29dof.xml"
      urdfFileName: "g1_29dof_fakehand.urdf"
